### ISSUE TITLE
string_replace_gpl3 is broken

### ISSUE THREAD

**Issue by orsonteodoro** [orsonteodoro/nano-ycmd#3]
Since this is broken, the multicore version is considered broken.  python's json decoder will complain about it:

2018-02-11 16:46:33,604 - INFO - Received completion request
2018-02-11 16:46:33,608 - INFO - Received extra conf ignore request
2018-02-11 16:46:34,910 - INFO - Received ready request
2018-02-11 16:46:34,926 - INFO - Received extra conf load request
2018-02-11 16:46:34,929 - INFO - Received event notification
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/ycmd/../bottle.py", line 862, in _handle
    return route.call(**args)
  File "/usr/lib64/python2.7/site-packages/ycmd/../bottle.py", line 1741, in wrapper
    rv = callback(*a, **ka)
  File "/usr/lib64/python2.7/site-packages/ycmd/../ycmd/watchdog_plugin.py", line 108, in wrapper
    return callback( *args, **kwargs )
  File "/usr/lib64/python2.7/site-packages/ycmd/../ycmd/hmac_plugin.py", line 70, in wrapper
    body = callback( *args, **kwargs )
  File "/usr/lib64/python2.7/site-packages/ycmd/../ycmd/handlers.py", line 59, in EventNotification
    request_data = RequestWrap( request.json )
  File "/usr/lib64/python2.7/site-packages/ycmd/../bottle.py", line 166, in __get__
    if key not in storage: storage[key] = self.getter(obj)
  File "/usr/lib64/python2.7/site-packages/ycmd/../bottle.py", line 1124, in json
    return json_loads(b)
  File "/usr/lib64/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")

This is the debug spew for string_replace_gpl3 function:

string_replace_gpl3 find arg: LINE_NUM
string_replace_gpl3 replace arg: 4
string_replace_gpl3 out is currently (befor): 
j=0 running multicore sse2 compare threadid=0
used sse2 string_replace_gpl3 section
string_replace_gpl3 out is currently (after): {        "column
string_replace_gpl3 out is currently (befor): {        "column
j=0 running multicore sse2 compare threadid=0
used sse2 string_replace_gpl3 section
string_replace_gpl3 out is currently (after): {        "column_num": 14,      
string_replace_gpl3 out is currently (befor): {        "column_num": 14,      
j=0 running multicore sse2 compare threadid=0
used sse2 string_replace_gpl3 section
string_replace_gpl3 out is currently (after): {        "column_num": 14,        "event_name": 
string_replace_gpl3 out is currently (befor): {        "column_num": 14,        "event_name": 
j=0 running multicore sse2 compare threadid=0
used sse2 string_replace_gpl3 section
string_replace_gpl3 out is currently (after): {        "column_num": 14,        "event_name": "FileReadyToPars
string_replace_gpl3 out is currently (befor): {        "column_num": 14,        "event_name": "FileReadyToPars
j=0 running multicore sse2 compare threadid=0
used sse2 string_replace_gpl3 section
string_replace_gpl3 out is currently (after): {        "column_num": 14,        "event_name": "FileReadyToParse",        "file
string_replace_gpl3 out is currently (befor): {        "column_num": 14,        "event_name": "FileReadyToParse",        "file
j=0 running multicore sse2 compare threadid=0
string_replace_gpl3 out is currently (after): {        "column_num": 14,        "event_name": "FileReadyToParse",        "file_data": {		"FI
string_replace_gpl3 out is currently (befor): {        "column_num": 14,        "event_name": "FileReadyToParse",        "file_data": {		"FI
j=0 running multicore sse2 compare threadid=0
string_replace_gpl3 out is currently (after): {        "column_num": 14,        "event_name": "FileReadyToParse",        "file_data": {		"FILEPATH": {                "contents": "CONTENTS",                "filetypes": ["FI
string_replace_gpl3 out is currently (befor): {        "column_num": 14,        "event_name": "FileReadyToParse",        "file_data": {		"FILEPATH": {                "contents": "CONTENTS",                "filetypes": ["FI
j=0 running multicore sse2 compare threadid=0
string_replace_gpl3 out is currently (after): {        "column_num": 14,        "event_name": "FileReadyToParse",        "file_data": {		"FILEPATH": {                "contents": "CONTENTS",                "filetypes": ["FILETYPES"]        	}	 },        "filepath": "FI
string_replace_gpl3 out is currently (befor): {        "column_num": 14,        "event_name": "FileReadyToParse",        "file_data": {		"FILEPATH": {                "contents": "CONTENTS",                "filetypes": ["FILETYPES"]        	}	 },        "filepath": "FI
j=0 running multicore sse2 compare threadid=0
string_replace_gpl3 out is currently (after): {        "column_num": 14,        "event_name": "FileReadyToParse",        "file_data": {		"FILEPATH": {                "contents": "CONTENTS",                "filetypes": ["FILETYPES"]        	}	 },        "filepath": "FILEPATH",        "line_num": 
string_replace_gpl3 out is currently (befor): {        "column_num": 14,        "event_name": "FileReadyToParse",        "file_data": {		"FILEPATH": {                "contents": "CONTENTS",                "filetypes": ["FILETYPES"]        	}	 },        "filepath": "FILEPATH",        "line_num": 
j=0 running multicore sse2 compare threadid=0
string_replace_gpl3 out is currently (after): {        "column_num": 14,        "event_name": "FileReadyToParse",        "file_data": {		"FILEPATH": {                "contents": "CONTENTS",                "filetypes": ["FILETYPES"]        	}	 },        "filepath": "FILEPATH",        "line_num": LINE_NUM}
string_replace_gpl3 final: {        "column_num": 14,        "event_name": "FileReadyToParse",        "file_data": {		"FILEPATH": {                "contents": "CONTENTS",                "filetypes": ["FILETYPES"]        	}	 },        "filepath": "FILEPATH",        "line_num": LINE_NUM}

The string_replace_gpl3 final LINE_NUM should be 4.

The cause of the bug is that it is not doing single byte check after scanning ncores * register_width.

**Comment by orsonteodoro** [comment]
fixed: https://github.com/orsonteodoro/nano-ycmd/commit/61b82be3e3b18b642ef75a1eee693f890127ba77
